.PHONY: clean All

All:
	@echo "----------Building project:[ Section15 - Debug ]----------"
	@cd "Section15" && "$(MAKE)" -f  "Section15.mk"
clean:
	@echo "----------Cleaning project:[ Section15 - Debug ]----------"
	@cd "Section15" && "$(MAKE)" -f  "Section15.mk" clean
