.PHONY: clean All

All:
	@echo "----------Building project:[ FourInARow - Debug ]----------"
	@cd "FourInARow" && "$(MAKE)" -f  "FourInARow.mk"
clean:
	@echo "----------Cleaning project:[ FourInARow - Debug ]----------"
	@cd "FourInARow" && "$(MAKE)" -f  "FourInARow.mk" clean
