.PHONY: clean All

All:
	@echo "----------Building project:[ MyChallengeSolution - Debug ]----------"
	@cd "MyChallengeSolution" && "$(MAKE)" -f  "MyChallengeSolution.mk"
clean:
	@echo "----------Cleaning project:[ MyChallengeSolution - Debug ]----------"
	@cd "MyChallengeSolution" && "$(MAKE)" -f  "MyChallengeSolution.mk" clean
